language: java
jdk: openjdk11
cache:
  directories:
  - "$HOME/.m2"

script:
- mvn --settings .travis/settings.xml -DskipTests=true -Dmaven.javadoc.skip=true -B -U -V deploy

before_deploy:
- mkdir -p /tmp/travis
- openssl aes-256-cbc -K $encrypted_c26b694af5a7_key -iv $encrypted_c26b694af5a7_iv -in .travis/id_rsa.enc -out /tmp/travis/id_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/travis/id_rsa
- ssh-add /tmp/travis/id_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: bash .travis/deploy.sh
