language: java
jdk: openjdk11
cache:
  directories:
  - "$HOME/.m2"

install:
- echo 'avereon.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBAX0k5tSvrXVpKl7HNPIPglp6Kyj0Ypty6M3hgR783ViTzhRnojEZvdCXuYiGSVKEzZWr9oYQnLr03qjU/t0SNw=' >> $HOME/.ssh/known_hosts

script:
- mvn --settings .travis/settings.xml -DskipTests=true -Dmaven.javadoc.skip=true -B -U -V deploy

before_deploy:
- openssl aes-256-cbc -K $encrypted_c26b694af5a7_key -iv $encrypted_c26b694af5a7_iv -in .travis/id_rsa.enc -out /tmp/travis/id_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/travis/deploy_rsa
- ssh-add /tmp/travis/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: bash .travis/deploy.sh
