name: Avereon Seenc CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Fetch sources
      uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build
      env:
        AVN_REPO_USERNAME: ${{ secrets.AVN_REPO_USERNAME }}
        AVN_REPO_PASSWORD: ${{ secrets.AVN_REPO_PASSWORD }}
      run: mvn test -B -U -V --settings .github/settings.xml --file pom.xml
    - name: Deploy
      if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/stable' || github.base_ref == 'refs/heads/master' || github.base_ref == 'refs/heads/stable'
      env:
        AVN_GPG_PASSWORD: ${{ secrets.AVN_GPG_PASSWORD }}
        AVN_KEYSTORE_PASSWORD: ${{ secrets.AVN_KEYSTORE_PASSWORD }}
        AVN_REPO_USERNAME: ${{ secrets.AVN_REPO_USERNAME }}
        AVN_REPO_PASSWORD: ${{ secrets.AVN_REPO_PASSWORD }}
        GITHUB_REF: ${{ github.ref }}
      run: .github/deploy.sh
